// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHK5CtosuauI_zQIh0GiFajhbEm9nLlS4',
    appId: '1:1060894129891:web:e18b973b0a69317d9e8fd6',
    messagingSenderId: '1060894129891',
    projectId: 'practicepal-933ce',
    authDomain: 'practicepal-933ce.firebaseapp.com',
    storageBucket: 'practicepal-933ce.firebasestorage.app',
    measurementId: 'G-1XD0RK9PXD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyQ_5SDlG-eWM65W-ed7kUHG4ateWP9P8',
    appId: '1:1060894129891:android:74e6ebf90c285a309e8fd6',
    messagingSenderId: '1060894129891',
    projectId: 'practicepal-933ce',
    storageBucket: 'practicepal-933ce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxX9RjJ9FTY5SUT7e-4qOf_Q7bx7ItxYU',
    appId: '1:1060894129891:ios:7d5fa0786bb98b619e8fd6',
    messagingSenderId: '1060894129891',
    projectId: 'practicepal-933ce',
    storageBucket: 'practicepal-933ce.firebasestorage.app',
    iosBundleId: 'com.example.practicepal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxX9RjJ9FTY5SUT7e-4qOf_Q7bx7ItxYU',
    appId: '1:1060894129891:ios:7d5fa0786bb98b619e8fd6',
    messagingSenderId: '1060894129891',
    projectId: 'practicepal-933ce',
    storageBucket: 'practicepal-933ce.firebasestorage.app',
    iosBundleId: 'com.example.practicepal',
  );
}
